# 数据库配置文件

# Redis配置
redis:
  url: "redis://localhost:6379/0"
  password: ""
  max_connections: 100
  socket_timeout: 30
  socket_connect_timeout: 30
  retry_on_timeout: true
  health_check_interval: 30

# MongoDB配置
mongodb:
  uri: "mongodb://localhost:27017/"
  database: "crawler_db"
  username: ""
  password: ""
  collections:
    raw_data: "raw_epidemic_data"
    processed_data: "processed_epidemic_data"
    logs: "crawler_logs"
    tasks: "crawler_tasks"

## 已移除 PostgreSQL 配置

# 连接池配置
connection_pools:
  redis:
    max_connections: 100
    retry_on_timeout: true

  mongodb:
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time_ms: 30000

  # 已移除 postgresql 连接池配置
