# 北京市疾病预防控制中心数据提取配置
site_name: "北京市疾病预防控制中心"
base_url: "https://www.bjcdc.org"
encoding: "utf-8"
description: "北京市疾病预防控制中心官方网站数据提取配置"

# 字段提取配置
fields:
  # 标题提取
  title:
    method: xpath
    selector: "//title/text() | //p[@class='content_rt_top']/text()"
    type: string
    required: true
    description: "页面标题"

  # 新闻链接列表
  news_links:
    method: xpath
    selector: "//ul[@class='content_list']//li//a/@href"
    type: string
    multiple: true
    description: "新闻详情页链接"

  # 新闻标题列表
  news_titles:
    method: xpath
    selector: "//ul[@class='content_list']//li//a/text()[normalize-space()]"
    type: string
    multiple: true
    description: "新闻标题列表"

  # 发布日期列表
  publish_dates:
    method: xpath
    selector: "//ul[@class='content_list']//li//span/text()"
    type: string
    multiple: true
    description: "发布日期列表"

  # 疾病关键词提取
  disease_keywords:
    method: regex
    selector: "(流感|新冠|COVID|肺炎|结核|艾滋|HIV|肝炎|手足口|诺如|轮状|腹泻|发热|咳嗽|传染病|疫情|病毒|细菌|疫苗|接种|防控|监测|预警|爆发|流行|感染|确诊|疑似|密接|隔离|消毒|防护)"
    type: string
    multiple: true
    description: "疾病相关关键词"

  # 地区信息（北京各区）
  beijing_districts:
    method: regex
    selector: "(北京|朝阳|海淀|丰台|石景山|门头沟|房山|通州|顺义|昌平|大兴|怀柔|平谷|密云|延庆|东城|西城|经开区|亦庄)"
    type: string
    multiple: true
    description: "北京市各区县信息"

  # 发布日期
  publish_date:
    method: xpath
    selector: "//span[@class='time']/text() | //div[@class='date']/text() | //*[contains(@class,'date')]/text() | //*[contains(text(),'发布时间')]/following-sibling::*/text() | //*[contains(text(),'时间')]/text()"
    type: date
    description: "发布时间"

  # 来源
  source:
    method: xpath
    selector: "//span[@class='source']/text() | //div[@class='source']/text() | //*[contains(text(),'来源')]/following-sibling::*/text()"
    type: string
    description: "信息来源"

  # 作者
  author:
    method: xpath
    selector: "//span[@class='author']/text() | //div[@class='author']/text() | //*[contains(text(),'作者')]/following-sibling::*/text()"
    type: string
    description: "作者信息"

  # 摘要
  summary:
    method: xpath
    selector: "//div[@class='summary']/text() | //p[@class='summary']/text() | //div[@class='abstract']/text() | //meta[@name='description']/@content"
    type: string
    description: "文章摘要"

  # 分类/栏目
  category:
    method: xpath
    selector: "//div[@class='category']/text() | //span[@class='category']/text() | //nav//a[@class='active']/text()"
    type: string
    description: "文章分类"

  # 点击量/浏览量
  view_count:
    method: regex
    selector: "浏览[：:]?\\s*(\\d+)\\s*次|点击[：:]?\\s*(\\d+)\\s*次|阅读[：:]?\\s*(\\d+)\\s*次"
    type: integer
    description: "浏览次数"

  # 疫情相关数据提取
  confirmed_cases:
    method: regex
    selector: "确诊[病例]*[：:]?\\s*(\\d+)\\s*例"
    type: integer
    description: "确诊病例数"

  suspected_cases:
    method: regex
    selector: "疑似[病例]*[：:]?\\s*(\\d+)\\s*例"
    type: integer
    description: "疑似病例数"

  death_cases:
    method: regex
    selector: "死亡[病例]*[：:]?\\s*(\\d+)\\s*例"
    type: integer
    description: "死亡病例数"

  recovered_cases:
    method: regex
    selector: "治愈[出院]*[病例]*[：:]?\\s*(\\d+)\\s*例|康复[：:]?\\s*(\\d+)\\s*例"
    type: integer
    description: "治愈病例数"

  # 地区信息
  region:
    method: regex
    selector: "(北京|朝阳|海淀|丰台|石景山|门头沟|房山|通州|顺义|昌平|大兴|怀柔|平谷|密云|延庆|东城|西城)"
    type: string
    multiple: true
    description: "涉及地区"

  # 健康相关关键词
  health_keywords:
    method: regex
    selector: "(疫情|防控|病毒|感染|隔离|检测|疫苗|核酸|抗原|健康|预防|消毒|口罩|发热|咳嗽|症状)"
    type: string
    multiple: true
    description: "健康相关关键词"

  # 图片链接
  images:
    method: xpath
    selector: "//img/@src"
    type: string
    multiple: true
    description: "图片链接"

  # 附件链接
  attachments:
    method: xpath
    selector: "//a[contains(@href, '.pdf') or contains(@href, '.doc') or contains(@href, '.xls') or contains(@href, '.zip')]/@href"
    type: string
    multiple: true
    description: "附件链接"

  # 相关链接
  related_links:
    method: xpath
    selector: "//div[@class='related']//a/@href | //div[@class='links']//a/@href"
    type: string
    multiple: true
    description: "相关链接"

# 分页配置
pagination:
  next_page_xpath: "//a[contains(text(), '下一页') or contains(text(), '下页') or contains(@class, 'next') or contains(text(), '>')]/@href"
  max_pages: 20
  page_param: "page"

# 链接跟进配置
follow_links:
  # 文章详情页
  article_detail:
    xpath: "//a[contains(@href, '/article/') or contains(@href, '/news/') or contains(@href, '/notice/')]/@href"
    max_depth: 2

  # 列表页
  list_page:
    xpath: "//a[contains(@href, '/list/') or contains(@href, 'list')]/@href"
    max_depth: 1

# 请求配置
request_settings:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"
    Accept-Encoding: "gzip, deflate, br"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"

  # 请求延迟
  delay: 3.0
  random_delay: true

  # 重试配置
  retry_times: 3
  retry_delay: 10.0

# 数据清洗配置
cleaning:
  # 文本清洗
  text:
    remove_html: true
    remove_special_chars: false
    max_length: 20000
    min_length: 5

  # 数字清洗
  number:
    min_value: 0
    max_value: 1000000
    as_integer: true

  # 日期清洗
  date:
    format: "%Y-%m-%d"

# 数据验证配置
validation:
  required_fields:
    - title
    - content
    - url

  field_rules:
    title:
      min_length: 5
      max_length: 200

    content:
      min_length: 20
      max_length: 100000

    confirmed_cases:
      min_value: 0
      max_value: 100000

# 质量评估配置
quality:
  weights:
    completeness: 0.3
    accuracy: 0.3
    consistency: 0.2
    timeliness: 0.1
    validity: 0.1

  thresholds:
    min_score: 0.5
    warning_score: 0.7
    good_score: 0.8

# 存储配置
storage:
  collection_name: "bjcdc_data"
  indexes:
    - field: "publish_date"
      order: -1
    - field: "region"
      order: 1
    - field: "confirmed_cases"
      order: -1
