# 辽宁省疾病预防控制中心网站配置
site_info:
  name: "辽宁省疾病预防控制中心"
  base_url: "http://www.lncdc.com/"
  description: "辽宁省疾病预防控制中心数据爬取"
  domains:
    - "www.lncdc.com"
  encoding: "utf-8"
  language: "zh-CN"

# 目标页面配置
start_urls:
  - url: "https://www.lncdc.com/lncdc/secondanylevel.html?group=%E5%8A%A8%E6%80%81%E4%BF%A1%E6%81%AF&cur=%E4%BC%A0%E6%9F%93%E7%97%85%E4%BF%A1%E6%81%AF&curtype=xwdt2&groupall=%E4%B8%AD%E5%BF%83%E5%8A%A8%E6%80%81%2C%E8%A1%8C%E4%B8%9A%E5%8A%A8%E6%80%81%2C%E5%9F%BA%E5%B1%82%E5%8A%A8%E6%80%81%2C%E4%BC%A0%E6%9F%93%E7%97%85%E4%BF%A1%E6%81%AF%2C%E7%AA%81%E5%8F%91%E4%BA%8B%E4%BB%B6%E5%93%8D%E5%BA%94"
    name: "传染病信息"
    type: "list_page"

# 页面类型检测配置
detection:
  page_types:
    list_page:
      url_patterns:
        - ".*/index\\.shtml$"
        - ".*/list.*\\.shtml$"
      content_features:
        min_links: 5
        keywords: ["要闻", "动态", "新闻"]
      structure_features:
        required_selectors:
          - "//*[contains(@class, 'content_list')]//li"
        min_elements:
          "//*[contains(@class, 'content_list')]//li//a": 3

    detail_page:
      url_patterns:
        - ".*/\\d+\\.shtml$"
        - ".*article.*"
      content_features:
        min_content_length: 500
      structure_features:
        required_selectors:
          - "//*[contains(@class, 'article')]//div[contains(@class, 'article_detail_con')]//p"

# 数据提取配置
extraction:
  # 通用字段提取
  fields:
    title:
      method: xpath
      selector: "//title/text() | //p[@class='content_rt_top']/text() | //h1/text()"
      type: string
      required: true
      description: "页面标题"

    content:
      method: xpath
      selector: "//div[@class='article_detail_con']//p/text() | //div[@class='content']//p/text()"
      type: string
      multiple: true
      required: false
      description: "页面内容"

    publish_date:
      method: xpath
      selector: "//span[@class='time']/text() | //div[@class='date']/text() | //*[contains(@class,'date')]/text()"
      type: date
      required: false
      description: "发布时间"

  # 列表页特定配置
  list_page:
    fields:
      page_title:
        method: css
        selector: "#curtitle"
        attr: text
        required: true

    list_items:
      container: ".bd li"
      max_items: 50
      fields:
        title:
          method: css
          selector: ".line-ellipsis"
          attr: text
        url:
          method: css
          selector: "a"
          attr: href
        click_selector:
          method: css
          selector: "a"
        date:
          method: css
          selector: ".time"
          attr: text

  # 详情页特定配置
  detail_page:
    fields:
      title:
        method: css
        selector: ".view1-box-title .title"
        attr: text
        required: true
      content:
        method: css
        selector: ".view1-box-main-content p"
        attr: text
        multiple: true
        required: true
      source:
        method: css
        selector: ".clearfix"
        type: string
        required: false
      publish_date:
        method: css
        selector: "body > div.page > div > div > div.main > div:nth-child(4) > div > div > div > div > div:nth-child(1) > div > div.info-left.fl > div:nth-child(1) > p:nth-child(2)"
        type: date
        required: false
      image_urls:
        method: css
        selector: ".view1-box-main-content img::attr(src)"
        type: url
        multiple: true
      file_urls:
        method: css
        selector: "a[href$='.pdf']::attr(href), a[href*='.pdf']::attr(href)"
        type: url
        multiple: true

# 请求配置
request:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"

  delays:
    download_delay: 0.5
    randomize_delay: true
    random_range: [0.5, 2.0]

  retry:
    retry_times: 3
    retry_delay: 5.0
  
  # Selenium 配置
  selenium:
    enabled: true # 为该站点启用 Selenium
    browser_type: "chrome" # 使用 Chrome 浏览器，也可以是 "firefox"
    headless: false # 以无头模式运行浏览器
    wait_time: 5 # 页面加载或元素出现的最大等待时间（秒），用于 SeleniumRequest 辅助类
    timeouts:
      implicit_wait: 3 # 隐式等待时间
      explicit_wait: 5 # 显式等待时间
      page_load: 5 # 页面加载超时时间
    crawling_strategy:
      delays:
        page_load_wait: 3 # 页面加载后额外等待时间
        after_click: 0.5 # 点击后额外等待时间

# 数据清洗配置
cleaning:
  text:
    remove_html: true
    remove_special_chars: false
    max_length: 50000
    min_length: 5

  urls:
    convert_to_absolute: true
    validate_urls: true

  dates:
    format: "%Y-%m-%d"
    timezone: "Asia/Shanghai"

# 数据验证配置
validation:
  required_fields:
    - title
    - url

  field_rules:
    title:
      min_length: 5
      max_length: 200

    content:
      min_length: 20
      max_length: 100000

    url:
      pattern: "^https?://"

# 存储配置

# 更新检测配置（可站点级覆盖）
update_detection:
  enable_content_dedup: true
  list_refresh_interval: 900

storage:
  collection_name: "lncdc_data"
  indexes:
    - field: "publish_date"
      order: -1
    - field: "url"
      unique: true
