# 国家卫健委网站配置

site_name: "国家卫生健康委员会"
base_url: "http://www.nhc.gov.cn"
encoding: "utf-8"

# 爬取配置
crawl_config:
  start_urls:
    - "http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml"  # 疫情通报
    - "http://www.nhc.gov.cn/xcs/yqfkdt/list_gzbd.shtml"  # 疫情防控动态
    - "http://www.nhc.gov.cn/xcs/zhengcwj/list_gzbd.shtml"  # 政策文件
  
  allowed_domains:
    - "nhc.gov.cn"
    - "www.nhc.gov.cn"

# 数据提取规则
fields:
  # 列表页字段
  list_title:
    method: xpath
    selector: "//ul[@class='zxxx_list']/li/a/@title"
    multiple: true
    
  list_links:
    method: xpath
    selector: "//ul[@class='zxxx_list']/li/a/@href"
    multiple: true
    
  list_dates:
    method: xpath
    selector: "//ul[@class='zxxx_list']/li/span/text()"
    multiple: true
  
  # 详情页字段
  title:
    method: xpath
    selector: "//div[@class='tit']/text()"
    type: string
    
  content:
    method: xpath
    selector: "//div[@id='xw_box']//text()"
    type: string
    multiple: true
    
  publish_date:
    method: xpath
    selector: "//div[@class='source']/span[1]/text()"
    type: date
    
  source:
    method: xpath
    selector: "//div[@class='source']/span[2]/text()"
    type: string
    
  # 疫情数据提取（从内容中）
  confirmed_cases:
    method: regex
    selector: "确诊病例(\\d+)例|累计确诊(\\d+)例|现有确诊病例(\\d+)例"
    type: integer
    
  death_cases:
    method: regex
    selector: "死亡病例(\\d+)例|累计死亡(\\d+)例|死亡(\\d+)例"
    type: integer
    
  recovered_cases:
    method: regex
    selector: "治愈出院病例(\\d+)例|累计治愈出院(\\d+)例|治愈(\\d+)例"
    type: integer

# 翻页配置
pagination:
  next_page_xpath: "//a[contains(text(), '下一页')]/@href"
  max_pages: 50
  
# 详情页链接配置
detail_links:
  selector: "//ul[@class='zxxx_list']/li/a/@href"

# 频率控制
rate_limit:
  delay: 2.0
  random_delay: true
  max_concurrent: 1

# 数据质量配置
quality_rules:
  required_fields:
    - title
    - content
    - publish_date
  
  validation_rules:
    title:
      min_length: 5
      max_length: 200
    content:
      min_length: 50
    confirmed_cases:
      min_value: 0
      max_value: 10000000
    death_cases:
      min_value: 0
      max_value: 1000000

# 去重配置
deduplication:
  method: "fingerprint"  # fingerprint, url, content
  fields: ["title", "publish_date", "content"]

# 存储配置
storage:
  mongodb:
    collection: "nhc_data"
  postgresql:
    table: "epidemic_data"
  
# 监控配置
monitoring:
  alert_on_errors: true
  max_error_rate: 0.1
  min_success_rate: 0.8

# 特殊处理规则
special_rules:
  # 内容清洗规则
  content_cleaning:
    remove_patterns:
      - "\\s+"  # 多余空白
      - "\\n+"  # 多余换行
    
    replace_patterns:
      "　": " "  # 全角空格替换为半角
  
  # 日期格式化
  date_formats:
    - "%Y-%m-%d"
    - "%Y年%m月%d日"
    - "%m月%d日"
  
  # 地区标准化
  region_mapping:
    "全国": "中国"
    "内地": "中国大陆"

# 错误处理
error_handling:
  retry_times: 3
  retry_delay: 5
  ignore_errors:
    - 404
    - 403
  
  fallback_selectors:
    title:
      - "//h1/text()"
      - "//title/text()"
    content:
      - "//div[@class='con']//text()"
      - "//div[@class='content']//text()"
