# 网站配置模板
# 复制此文件并重命名为具体网站名称，如 bjcdc.yaml

# 网站基本信息
site_info:
  name: "网站名称"
  description: "网站描述"
  domains:
    - "example.com"
    - "www.example.com"
  base_url: "https://www.example.com"
  encoding: "utf-8"
  language: "zh-CN"

# 起始URL配置（必需）
start_urls:
  - url: "https://www.example.com/news/list"
    name: "新闻列表"
    type: "list_page"
    description: "新闻列表页面"
  - url: "https://www.example.com/articles/index"
    name: "文章首页"
    type: "list_page"
    description: "文章列表页面"

# 页面类型检测配置
detection:
  page_types:
    # 列表页检测规则
    list_page:
      url_patterns:
        - ".*list.*"
        - ".*index.*"
        - ".*category.*"
      content_features:
        min_links: 5
        keywords: ["列表", "目录"]
        min_content_length: 1000
      structure_features:
        required_selectors:
          - "ul li a"
        min_elements:
          "a": 5

    # 详情页检测规则
    detail_page:
      url_patterns:
        - ".*detail.*"
        - ".*article.*"
        - ".*news.*"
      content_features:
        min_content_length: 2000
        keywords: ["内容", "正文"]
      structure_features:
        required_selectors:
          - ".content, .article, article"

# 数据提取配置
extraction:
  # 通用字段提取（适用于所有页面类型）
  fields:
    title:
      method: xpath  # xpath, css, regex
      selector: "//title/text() | //h1/text()"
      type: string   # string, integer, float, date, url
      required: true
      description: "页面标题"

    content:
      method: css
      selector: ".content p, .article p"
      type: string
      multiple: true
      required: false
      description: "页面内容"

    publish_date:
      method: regex
      selector: '\d{4}[-/年]\d{1,2}[-/月]\d{1,2}[日]?'
      type: date
      required: false
      description: "发布日期"

  # 列表页特定配置
  list_page:
    fields:
      page_title:
        method: css
        selector: "h1, .page-title"
        type: string
        required: true

    list_items:
      container: "ul li, .news-list li"
      max_items: 50
      fields:
        title:
          method: css
          selector: "a"
          attr: text
        url:
          method: css
          selector: "a"
          attr: href
        date:
          method: css
          selector: ".date, .time"
          attr: text

  # 详情页特定配置
  detail_page:
    fields:
      article_title:
        method: css
        selector: "h1, .article-title"
        type: string
        required: true

      article_content:
        method: css
        selector: ".article-content p, .content p"
        type: string
        multiple: true
        required: true

      author:
        method: css
        selector: ".author, .writer"
        type: string
        required: false

      tags:
        method: css
        selector: ".tags a, .tag"
        type: string
        multiple: true
        required: false

# 请求配置
request:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"

  delays:
    download_delay: 2.0
    randomize_delay: true
    random_range: [1.0, 3.0]

  retry:
    retry_times: 3
    retry_delay: 5.0

# 数据清洗配置
cleaning:
  text:
    remove_html: true
    remove_special_chars: false
    max_length: 50000
    min_length: 5

  urls:
    convert_to_absolute: true
    validate_urls: true

  dates:
    format: "%Y-%m-%d"
    timezone: "Asia/Shanghai"

# 数据验证配置
validation:
  required_fields:
    - title
    - url

  field_rules:
    title:
      min_length: 5
      max_length: 200

    content:
      min_length: 20
      max_length: 100000

    url:
      pattern: "^https?://"

# 存储配置
storage:
  collection_name: "site_data"
  indexes:
    - field: "publish_date"
      order: -1
    - field: "url"
      unique: true

# 链接跟进规则
follow_rules:
  # 允许跟进的URL模式
  allow_patterns:
    - ".*\\.html$"
    - ".*\\.shtml$"
    - ".*/news/.*"
    - ".*/article/.*"

  # 禁止跟进的URL模式
  deny_patterns:
    - ".*\\.(jpg|jpeg|png|gif|pdf|doc|docx)$"
    - "javascript:"
    - "mailto:"
    - "#"

  # 最大跟进深度
  max_depth: 3

  # 每页最大跟进链接数
  max_links_per_page: 20
