# 云南省疾病预防控制中心网站配置
site_info:
  name: "云南省疾病预防控制中心"
  base_url: "https://www.yncdc.cn/"
  description: "云南省疾病预防控制中心数据爬取"
  domains:
    - "www.yncdc.cn"
  encoding: "utf-8"
  language: "zh-CN"

# 目标页面配置
start_urls:
  - url: "https://www.yncdc.cn/jkzt/jkts/crb/index.shtml"
    name: "云南省法定传染病疫情报告"
    type: "list_page"

# 页面类型检测配置
detection:
  page_types:
    list_page:
      url_patterns:
        - ".*/index\\.shtml$"
        - ".*/list.*\\.shtml$"
      content_features:
        min_links: 5
        keywords: ["要闻", "动态", "新闻"]
      structure_features:
        required_selectors:
          - '//div[contains(@class, "article__list-nobg")]'
        min_elements:
          '//div[contains(@class, "article__list-nobg")]//div[@class="article__title"]/span': 3

    detail_page:
      url_patterns:
        - ".*/\\d+\\.shtml$"
        - ".*article.*"
      content_features:
        min_content_length: 500
      structure_features:
        required_selectors:
          - '//*[contains(@class, "article")]//div[contains(@class, "article_detail_con")]//p'

# 数据提取配置
extraction:
  # 通用字段提取
  fields:
    title:
      method: xpath
      selector: '//title/text() | //p[@class="content_rt_top"]/text() | //h1/text()'
      type: string
      required: true
      description: "页面标题"

    content:
      method: xpath
      selector: '//div[@class="article_detail_con"]//p/text() | //div[@class="content"]//p/text()'
      type: string
      multiple: true
      required: false
      description: "页面内容"

    publish_date:
      method: xpath
      selector: '//span[@class="time"]/text() | //div[@class="date"]/text() | //*[contains(@class,"date")]/text()'
      type: date
      required: false
      description: "发布时间"

  # 列表页特定配置
  list_page:
    fields:
      page_title:
        method: css
        selector: ".mbox__head"
        type: string
        required: true

    list_items:
      container: ".article__list-nobg"
      max_items: 50
      follow: true
      fields:
        title:
          method: css
          selector: ".article__title span"
          type: string
        url:
          method: xpath
          selector: "./@data-link"
          type: url
        date:
          method: xpath
          selector: "concat(.//span[@class='article__year']/text(), '-', .//span[@class='article__day']/text())"
          type: string

  # 详情页特定配置
  detail_page:
    fields:
      title:
        method: css
        selector: ".article__title"
        required: true
      content:
        method: css
        selector: "p"
        multiple: true
        required: true
      source:
        method: css
        selector: ".article__other"
        type: string
        required: false
      publish_date:
        method: css
        selector: ".article__other"
        type: date
        required: false
      image_urls:
        method: css
        selector: '.xiahua img::attr(src)'
        type: url
        multiple: true
      file_urls:
        method: css
        selector: 'a[href$=".pdf"]::attr(href), a[href*=".pdf"]::attr(href)'
        type: url
        multiple: true

# 请求配置
request:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"

  delays:
    download_delay: 0.5
    randomize_delay: true
    random_range: [0.5, 1.0]

  retry:
    retry_times: 2
    retry_delay: 1.0

  # Selenium 配置
  selenium:
    enabled: true # 为该站点启用 Selenium
    browser_type: "chrome" # 使用 Chrome 浏览器，也可以是 "firefox"
    headless: false # 以无头模式运行浏览器
    wait_time: 5 # 页面加载或元素出现的最大等待时间（秒），用于 SeleniumRequest 辅助类
    timeouts:
      implicit_wait: 3 # 隐式等待时间
      explicit_wait: 5 # 显式等待时间
      page_load: 5 # 页面加载超时时间
    crawling_strategy:
      delays:
        page_load_wait: 3 # 页面加载后额外等待时间
        after_click: 0.5 # 点击后额外等待时间
    # anti_detection: # 可选：反检测配置
    #   user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    #   disable_images: false
    #   disable_javascript: false
    #   disable_automation_flags: false # 仅 Firefox

# 数据清洗配置
cleaning:
  text:
    remove_html: true
    remove_special_chars: false
    max_length: 50000
    min_length: 5

  urls:
    convert_to_absolute: true
    validate_urls: true

  dates:
    format: "%Y-%m-%d"
    timezone: "Asia/Shanghai"

# 数据验证配置
validation:
  required_fields:
    - title
    - url

  field_rules:
    title:
      min_length: 5
      max_length: 200

    content:
      min_length: 20
      max_length: 100000

    url:
      pattern: "^https?://"

# 存储配置

# 更新检测配置（可站点级覆盖）
update_detection:
  enable_content_dedup: true
  list_refresh_interval: 900

storage:
  collection_name: "yncdc_data"
  indexes:
    - field: "publish_date"
      order: -1
    - field: "url"
      unique: true
